import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  
  const cursorMotion = () => {
    const cursor = document.querySelector('.cursorFollow');
    document.addEventListener('mousemove', e => {
        cursor.setAttribute("style", "top: " + (e.pageY + 3) + "px; left: " + (e.pageX + 3) + "px;")
    })
}
  return (
    <div className='h-screen w-full p-10 overflow-hidden cursor-defaultTwo' onMouseMove={cursorMotion}>
      <Head>
        <title>NRG Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="logo-area w-full flex flex-col justify-center items-center h-[15vh] md:h-[15vh] ">
        <Image
          src={"/lovelogo.png"}
          width={250}
          height={200}
          alt='The logo'
        />
      </div>
      <div className="w-full h-[10vh] md:h-8 flex flex-col justify-center items-center">
        <h1 className='font-bold text-2xl md:text-3xl'>Select a country</h1>
      </div>

      <div className="flex flex-col w-full justify-center items-center  h-[75vh] gap-16
      md:flex md:flex-row md:justify-around">
        <Image
          src={"/image-kenya.gif"}
          width={450}
          height={200}
          alt='The logo'
          onClick={() => window.open('https://ke.nrg.radio', '_blank')}
        />
        <Image
          src={"/image-uganda.gif"}
          width={450}
          height={200}
          alt='The logo'
          onClick={() => window.open('https://kla.nrg.radio', '_blank')}
        />

      </div>


      <div className="cursorFollow w-[10px] h-[10px] bg-[#DD0E34] rounded-full absolute
        duration-300 ease-out"></div>
    </div>
  )
}
